- name: build docker image and push it to dockr hub
  hosts: localhost
  become: yes 
  become_user: yasa
  

  tasks:
  - name: build image
    command: docker build -t nodejs-pipeline .
    args:
       chdir: /home/yasa/devops/nodeserver

  - name: tag the image
    command: docker tag nodejs-pipeline yasadocker/nodejs-pipeline:latest


  - name: push the built image to dockerhub
    command: docker push yasadocker/nodejs-pipeline:latest


  - name: delete the built image and the taged one
    command: docker rmi nodejs-pipeline yasadocker/nodejs-pipeline:latest